### PR TITLE
Minio, Golang and Flutter files

### PR DESCRIPTION
**Pull request by srs-sudeep**
1. This file sharing app is based on intranet with aws based S3 object storage server system.
2. For the object storage I am using Minio.
3. For backend Golang is used which uses minio and net http package.
4. For frontend Flutter is used to make it cross platform and it uses file_picker and clipboard module.

### CODE REVIEW

**Comment by chaitanyabisht** [comment]
Please omit secrets from your code

**Comment by chaitanyabisht** [comment]
Remove the executable binary from your repo as well. Add it to the gitignore and since you have already committed the binary in your repo, you need to remove it from tracking first.

**Comment by srs-sudeep** [comment]
This basic file-sharing app that  runs on Golang with minio as s3 based object storage server with flutter as the front end for cross-platform usability. Flutter uses various packages including file_picker http etc while golang uses minio and os.

**Comment by chaitanyabisht** [comment]
@srs-sudeep The blog is not supposed to be here. It will be put in a different repo which we will tell you shortly.

**Comment by chaitanyabisht** [comment]
Also please write the summary of this PR briefly in points in the comments.

**Comment by chaitanyabisht** [comment]
Add .vscode to gitignore as well

**Comment by chaitanyabisht** [comment]
You added it in Go folder, you need to add it in root folder to ignore .vscode

**Comment by chaitanyabisht** [comment]
Now that you've added the correct gitignore, please remove the .vscode from Git tracking as it was created prior to adding it to gitignore

**Pull request merged**
